name: Scrape Maricopa Charges (150000–170000 only)

on:
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install beautifulsoup4 gspread google-auth requests

      - name: Run scraper for 150k–170k
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
        run: |
          echo "$GOOGLE_CREDS" > google-creds.json
          p
